### ISSUE TITLE
Lab1

### ISSUE THREAD

**Issue by fantkolja** [mvyu222/Design-Patterns#1]
- Would be nice to have links in the README
- The arrows here have wrong direction and lines 
![image](https://github.com/mvyu222/Design-Patterns/assets/13898415/dd62e0bc-cb44-41a3-a659-313a675a9558)

**Comment by mvyu222** [comment]
Виправив, гілка : master, коміт :  29a289f

https://github.com/mvyu222/Design-Patterns/blob/master/lab1/diagrams.png
